[theme]
primaryColor = "#0078D4" # Microsoft Blue
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2127"
textColor = "#FAFAFA"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"
